### ISSUE TITLE
FACSvatar-Blender doesn't show up in Add-ons after selecting .zip file

### ISSUE THREAD

**Issue by Animixer** [NumesSanguis/FACSvatar-Blender#1]
Hi, I am running Blender 2.81 (sub 16) on Windows 10 Enterprise

After selecting the FACSvatar-Blender-0.4.0-alpha.zip file under Edit>Preferences>Add-ons>Install... FACSvatar does not appear in the list of add-ons. Terminal output reads as follows:

Modules Installed () from '...\\FACSvatar-Blender-0.4.0-alpha.zip' into 'C:\\<several directories>\\AppData\\Roaming\\Blender Foundation\\Blender\\2.81\\scripts\\addons'

**Comment by NumesSanguis** [comment]
Thank you for your bug report, I could reproduce the bug and also found out how to solve it.

It seems that the issue is with the `.zip` from the releases page. When you download that .zip, inside there is a folder named `FACSvatar-Blender-0.4.0-alpha`. It seems that Blender has trouble with `.` in folder names.

What you can do:
1. On the [repo page](https://github.com/NumesSanguis/FACSvatar-Blender), click the green "Clone or download" button --> Download ZIP.
2. Git clone this repository and turn it into a .zip
3. UnZIP the .zip from the release page, rename the folder from `FACSvatar-Blender-0.4.0-alpha` to something like `FACSvatar-Blender` and ZIP it again.

Then import the zip obtained with the above methods into Blender.

**Comment by NumesSanguis** [comment]
Ok, I found out that I can rename the version from `v0.4.0` to `v0_4_0`. The .zip from the release page should work now as well.

**Comment by Animixer** [comment]
Great, that did the trick!

Thank you very much
